/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SpamResult = IDL.Record({
  'reasons' : IDL.Vec(IDL.Text),
  'snippet' : IDL.Text,
  'isSpam' : IDL.Bool,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
  'confidence' : IDL.Float64,
});
export const HistoryEntry = IDL.Record({
  'id' : IDL.Nat,
  'snippet' : IDL.Text,
  'isSpam' : IDL.Bool,
  'timestamp' : IDL.Int,
  'confidence' : IDL.Float64,
});

export const idlService = IDL.Service({
  'analyzeMessage' : IDL.Func([IDL.Text], [SpamResult], []),
  'clearHistory' : IDL.Func([], [], []),
  'getHistory' : IDL.Func([], [IDL.Vec(HistoryEntry)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SpamResult = IDL.Record({
    'reasons' : IDL.Vec(IDL.Text),
    'snippet' : IDL.Text,
    'isSpam' : IDL.Bool,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
    'confidence' : IDL.Float64,
  });
  const HistoryEntry = IDL.Record({
    'id' : IDL.Nat,
    'snippet' : IDL.Text,
    'isSpam' : IDL.Bool,
    'timestamp' : IDL.Int,
    'confidence' : IDL.Float64,
  });
  
  return IDL.Service({
    'analyzeMessage' : IDL.Func([IDL.Text], [SpamResult], []),
    'clearHistory' : IDL.Func([], [], []),
    'getHistory' : IDL.Func([], [IDL.Vec(HistoryEntry)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };